// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2026/5/5 15:01:09
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["G:/trae/waiweb/components/**/*.{vue,js,jsx,mjs,ts,tsx}","G:/trae/waiweb/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","G:/trae/waiweb/components/**/*.{vue,js,jsx,mjs,ts,tsx}","G:/trae/waiweb/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","G:/trae/waiweb/plugins/**/*.{js,ts,mjs}","G:/trae/waiweb/composables/**/*.{js,ts,mjs}","G:/trae/waiweb/utils/**/*.{js,ts,mjs}","G:/trae/waiweb/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","G:/trae/waiweb/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","G:/trae/waiweb/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","G:/trae/waiweb/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;